// flow-typed signature: ab2e9b90921967344985f72b5bd1ee8c
// flow-typed version: <<STUB>>/electron-winstaller_v^2.5.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-winstaller'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-winstaller' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-winstaller/lib/fs-utils' {
  declare module.exports: any;
}

declare module 'electron-winstaller/lib/index' {
  declare module.exports: any;
}

declare module 'electron-winstaller/lib/spawn-promise' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-winstaller/lib/fs-utils.js' {
  declare module.exports: $Exports<'electron-winstaller/lib/fs-utils'>;
}
declare module 'electron-winstaller/lib/index.js' {
  declare module.exports: $Exports<'electron-winstaller/lib/index'>;
}
declare module 'electron-winstaller/lib/spawn-promise.js' {
  declare module.exports: $Exports<'electron-winstaller/lib/spawn-promise'>;
}
