// flow-typed signature: cee7f1d79b125449ec24be6277a36e19
// flow-typed version: <<STUB>>/node-cmd_v^1.2.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-cmd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-cmd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-cmd/cmd' {
  declare module.exports: any;
}

declare module 'node-cmd/commandline' {
  declare module.exports: any;
}

declare module 'node-cmd/example/basic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-cmd/cmd.js' {
  declare module.exports: $Exports<'node-cmd/cmd'>;
}
declare module 'node-cmd/commandline.js' {
  declare module.exports: $Exports<'node-cmd/commandline'>;
}
declare module 'node-cmd/example/basic.js' {
  declare module.exports: $Exports<'node-cmd/example/basic'>;
}
